name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  ai-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Check out the repository code
      - name: Generate YAML with AI
        run: python generate_yaml.py  # Run the AI script to generate deploy.yml

  build:
    needs: ai-generate  # Ensure this job runs after the AI generation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [node, python, java]  # Define which languages to build

    steps:
      - uses: actions/checkout@v2

      # Node.js build step
      - name: Set up Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cd node-app && npm install && npm run build  # Build Node.js app

      # Python build step
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          cd python-app
          python app.py  # Run the Python app

      # Java build step
      - name: Set up Java
        if: matrix.language == 'java'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - run: |
          cd java-app
          mvn clean install  # Build Java app

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job runs after the build job

    steps:
      - name: Deploy to Server
        run: echo "Deploying applications..."  # Replace with your actual deploy commands
