name: Generate YAML with GenAI

on:
  push:
    branches:
      - main

jobs:
  generate-yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate YAML file
        run: |
          curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer YOUR_API_KEY" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "Generate a CI/CD YAML file for a Node.js, Python, and Java application."}]
            }' > generated.yml

      - name: Use generated YAML
        run: cat generated.yml
